# ---------------------------------------------------------------------------- #
# Model
# ---------------------------------------------------------------------------- #
model:
  value: SuperTinyFC
input_type:
  value: volume
input_shape:
  value: 5,5,5
input_crop:
  value: zyx
crop_side:
  value: 5

loss:
  value: BCEWithLogitsLoss
loss_weight:
  value: 5

optimizer:
  value: Adam
optimizer_lr:
  value: 0.0002

# ---------------------------------------------------------------------------- #
# Data
# Human segmentations:
#        Zhuowei:
#        https://synapse.isrd.isi.edu/chaise/record/#1/Zebrafish:Image%20Region/RID=1-1VX8
#        https://synapse.isrd.isi.edu/chaise/record/#1/Zebrafish:Image%20Region/RID=1-1VXC
#        Olivia:
#        https://synapse.isrd.isi.edu/chaise/record/#1/Zebrafish:Image%20Region/RID=1-1VWT
#        https://synapse.isrd.isi.edu/chaise/record/#1/Zebrafish:Image%20Region/RID=1-1VWW
#        ML segmented, then human corrected:
#        https://synapse.isrd.isi.edu/chaise/record/#1/Zebrafish:Image%20Region/RID=1-1WH8
#        https://synapse.isrd.isi.edu/chaise/record/#1/Zebrafish:Image%20Region/RID=1-1WHA
# ---------------------------------------------------------------------------- #:
normalization:
  value: standardise by fish
drop_unsegmented:
  value: all
augmentation:
  value: True

data_train:
  value:
    - 1-1WHA
    - 1-1VWT
data_valid:
  value:
    - 1-1WHA
    - 1-1VWT
data_test:
  value:
    - 1-1VXC

# ---------------------------------------------------------------------------- #
# Training
# ---------------------------------------------------------------------------- #
batch_size:
  value: 500 # batch size Per GPU
num_workers:
  value: 0
max_epochs:
  value: 20

accelerator:
  value: 'gpu'

seed:
  value: NA
deterministic:
  value: False

